namePrefix: miniflux-

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: deployment
  - path: patch-service.yaml
    target:
      kind: Service
      name: service
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: ingress
  - path: patch-cert.yaml
    target:
      kind: ManagedCertificate
      name: cert
