apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: seafile-backend-config
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    type: HTTP
    requestPath: /accounts/login/