apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: bewcloud-default-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT