baseURL = 'http://j15r.com/'
languageCode = 'en-us'
title = 'Joel Webber - Personal Site'
theme = 'terminal'

[params]
	themeColor = "green"
	showMenuItems = 1

[languages.en.params.logo]
      logoText = "J15R"
      logoHomeLink = "/"

[[languages.en.menu.main]]
	identifier = "about"
	name = "About"
	url = "/about"
