apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo  # GKE default SSD storage class
  resources:
    requests:
      storage: 10Gi  # Adjust based on your needs